### ISSUE TITLE
A couple RSS thoughts

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#18]
**Plain author stored as [author][email]**

This happens with the following two feeds:
	https://www.cbc.ca/cmlink/rss-topstories
	http://www.thestar.com/content/thestar/feed.RSSManagerServlet.articlestopstories.rss
	
Both feeds store the author as a plain string. E.g., ```<item><author>Author Name</author></item>```
	
When I parse these feeds using: ```Parse_This_RSS::parse($feed,$url);```  the author information is stored as ```[author][email] = "Author Name"```
	
As a result, These feeds have no displayed author name in Monocle (and probably other clients, haven't checked yet)

**Multi-author feed issues**

Some items in thestar.com's feed have an empty ```<author></author>``` field.  As a result, they are stored without any author at all.  It would be good to fallback to the feed title for items that do not have any author.
	
Additionally, for multi-author feeds it would be nice to have the feed title used in some way if it differsfrom the author name. E.g. with the following item from CBC's feed:
```
<item cbc:type="story" cbc:deptid="2.637" cbc:syndicate="true">
      <title><![CDATA['I was beginning to lose hope': Woman battles bank for 2 years for information on her own account]]></title>
      <link>https://www.cbc.ca/news/business/woman-fights-bank-for-financial-records-1.4895631?cmp=rss</link>
      <guid isPermaLink="false">1.4895631</guid>
      <pubDate>Sun, 11 Nov 2018 20:00:00 EST</pubDate>
      <author>Rosa Marchitelli</author>
      <category>News/Business</category>
      <description>
        <![CDATA[
                        <img src='https://i.cbc.ca/1.4895862.1541710909!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_460/rhonda-mcmillan.jpg' alt='Rhonda McMillan' width='460' title='Rhonda McMillan fought for years to get a document she believes shows unauthorized activity on her account. ' height='259' />                <p>An Edmonton woman is speaking out about a two-year battle with her bank to access information about her account after she noticed a questionable transaction.</p>
        ]]>
      </description>
</item>
```
In the above case, the author will be stored as Rosa Marchitelli, but if I have a channel of various news feeds, I would also want to know the source website.  In Yarns' RSS parser, I would supplement the post author with the feed title (if they are different).  So in the case of CBC's feed, I would check the ```<channel><title>``` field, which contains
```<![CDATA[CBC | Top Stories News ]]>```
	
And then store the post author as "Rosa Marchitelli | CBC | Top Stories News"

Not sure if that's the best solution, but I think it's better than having the author name on its own

**Comment by dshanske** [comment]
The second property would be publication, which I usually store separately in citations

**Comment by dshanske** [comment]
Resolved in latest commit
