### ISSUE TITLE
fetch_feeds notes

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#20]
Switching over Yarns' search function to use Parse-This's fetch_feeds()

Works smoothly but I noticed two issues:

## 1 with tantek.com

fetch_feeds finds the atom feed on tantek.com, but does not return a microformats feed for tantek.com itself - I presume this will be fixed once the parse() function better handles tantek's site

## 2 with aaronparecki.com
PHP Notice:
```<b>Notice</b>:  Undefined index: feed in <b>/home4/karmaco1/public_html/microsub-dev/wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this.php</b> on line <b>215</b>```

This occurs because aaronparecki.com includes two linked feeds with `type = "feed"`.
The sorting algorithm in `fetch_feeds` does not account for that feed type.

A few possibilities
- type = "feed" could be interpreted as type = "microformats"
- If the feed type is not understood, Parse-This could go fetch the feed itself and run its own feed type detection
- If an unknown feed type is encountered, it could be returned as-is by fetch_feeds and sorted at the bottom of the list.  In this case, it would be necessary to account for unknown feed types in the parse function and/or in  applications that rely on parse-this

**Comment by dshanske** [comment]
I had the hardest time with tantek.com, if you check the dev chat logs.

**Comment by dshanske** [comment]
I will see about changing it to type Microformats.

**Comment by dshanske** [comment]
I consider it something we'll iterate on over time.

**Comment by jackjamieson2** [comment]
Just looked over your discussion with gRegorLove — I like the proposal to find all three feeds, and then be able to select them by id (or another identifier).

**Comment by dshanske** [comment]
https://github.com/microformats/php-mf2/pull/207

**Comment by dshanske** [comment]
It is in the works. If it merges it will make things easier.
