### ISSUE TITLE
Cached mf2 posts have no data

### ISSUE THREAD

**Issue by ngm** [dshanske/parse-this#25]
Using Post Kind 3.1.2 (and earlier versions), my posts with metadata don't display correctly on the individual post page.  They display OK on the main feed.

From what I can see the caching of MF2_Post doesn't work correctly for me, and cached results come back with empty values.

If I comment out [the line where the MF2_Post is cached](https://github.com/dshanske/parse-this/blob/master/includes/class-mf2-post.php#L78), the posts display OK.

I've documented it a little here: https://github.com/ngm/doubleloop.net/issues/8

**Comment by dshanske** [comment]
Is this after I fixed the missing _?

**Comment by dshanske** [comment]
There is a similar issue reported where the cache is not updating. Bumping this up

**Comment by dshanske** [comment]
I removed caching for now.
