### ISSUE TITLE
"unknown error" in fetch_feeds

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#30]
I've tried to search for feeds on a few sites that return 

{"code":"unknown error","message":null,"data":null}

- firstmonday.org
- boffosocko.com
- https://quickthoughts.jgregorymcverry.com/  (Although I've long had problems with this domain so I think this may be a separate issue)

**Comment by dshanske** [comment]
The issue is redirects. It was set to only allow one redirect.  Also, it wasn't surfacing the retrieval errors and now it does.
