### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by mrkrndvs** [dshanske/parse-this#31]
For the last week or so I have been having issues with parsing sites. Where I was getting some information in the past, I am not getting very little.

For example:

https://wiobyrne.com/the-case-for-anonymity-online/ produces
{“type”:”entry”,”syndication”:”https:\/\/medium.com\/@wiobyrne\/how-to-respond-to-trolling-behaviors-c27d269330e4″,”post-type”:”note”}

[Organizational Agility](https://dculberh.wordpress.com/2019/01/13/organizational-agility/)
{“type”:”feed”,”uid”:”https:\/\/dculberh.wordpress.com\/2019\/01\/13\/organizational-agility\/#page”}

&gt; [Weeknote 02/2019](http://dougbelshaw.com/blog/2019/01/12/weeknote-02-2019/)

{“category”:[“weeknotes”,”weeknote”,”work”],”type”:”entry”,”post-type”:”note”}

I have this strange feeling that it is not [Parse This](https://collect.readwriterespond.com/parse-this/) that is the problem, but it is where I am noticing the issue.

**Comment by dshanske** [comment]
On the first one, look at it in an MF2 parser. That is what is there.

Same on the second one. I have fallbacks for OGP parsing, but not when there are some microformats...even if empty ones. Should look to shift over in cases like this.

**Comment by dshanske** [comment]
Resolved. The HTML parser tries earlier in the process.
