### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#33]
I get a phpnotice when parsing boffosocko.com/blog/ or jackjamieson.net using Yarns. Probably with other feeds too - I temporarily bypassed the offending line so I could test some other parts of Yarns though

Notice: Undefined index: url in /.../wp-content/plugins/yarns-microsub-server/vendor/parse-this/includes/class-parse-this-mf2.php on line 628

(I posted this issue to Yarns previously, but realized I should post it here)
https://github.com/jackjamieson2/yarns-microsub-server/issues/52#issuecomment-453236469

**Comment by dshanske** [comment]
Resolved
