### ISSUE TITLE
PubMed parsing

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/parse-this#36]
I would think that a major information hub like PubMed would have better metadata given it's position in the research space but apparently not. It returns a bit of data, but could be way better.

Example page: https://www.ncbi.nlm.nih.gov/pubmed/17083004

(Originally published at https://boffosocko.com/2019/03/02/pubmed-parsing/)

**Comment by dshanske** [comment]
Got a few more properties out for you.
