### ISSUE TITLE
fetch_feeds speed

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#40]
I noted in https://github.com/jackjamieson2/yarns-microsub-server/issues/64#issuecomment-487696842 that Yarns is now taking a long time to find feeds on a given URL.

I looked into this and discovered that the `fetch_feeds()` function in Parse-This tends to have long execution time, and this is mostly due to https://github.com/dshanske/parse-this/blob/master/includes/class-parse-this.php#L209:

```
// Check to see if the current page is an h-feed
$this->parse( array( 'feed' => true ) );
```

My sense is that running `parse()` at this point is a bit overkill for detecting feeds. Would you be open to streamlining this?  If so, I'd be happy to make an attempt and submit a PR

**Comment by dshanske** [comment]
I noticed an oddity about this. When I have Post Kinds loaded, it seemed to run faster than when I didn't

**Comment by dshanske** [comment]
Thinking of moving this to its own class
