### ISSUE TITLE
['summary'] contains HTML

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#42]
From https://github.com/aaronpk/Monocle/issues/40

When parsing https://ruk.ca/rss/feedburner.xml, Parse-This returns HTML in the 'summary' field, which should be plain text.

I have a couple suggestions for the get_item() function at https://github.com/dshanske/parse-this/blob/master/includes/class-parse-this-rss.php#L70

1. The summary item should be wrapped with wp_strip_all_tags. 

2. In this feed, the <description> field contains HTML, which is an error as far as I know, but one I think we should accommodate.  In which case, I suggest removing the `true` argument when calling `get_content()`.  This will allow the content fields to be populated by <description>, and will preserve HTML

e.g. 

```
$return     = array(
	...
	'summary'     => wp_strip_all_tags($item->get_description( true )),
	'content'     => array_filter(
		array(
			'html' => htmlspecialchars( $item->get_content( ) ),
			'text' => wp_strip_all_tags( $item->get_content( ) ),
		)
	),
	...
);
```

I can submit as a PR if you prefer, thought I'd talk it through first though

**Comment by jackjamieson2** [comment]
I added a branch to my fork of Parse-This in case it's a useful reference: https://github.com/jackjamieson2/parse-this/tree/rss_parsing

Implements my suggestions from above, decodes special characters in a few fields, and copies the sanitization code from `Parse_This_MF2::parse_html_value()` - I think this should be the same in both RSS and MF2 parsers, but I might be wrong

**Comment by dshanske** [comment]
You are correct that Microsub defines summary as plaintext even if MF2 doesn't

**Comment by dshanske** [comment]
Many of those fields are supposed to be plaintext, so we should be able to strip them
