### ISSUE TITLE
Parse-This duplicated in "IndieWeb" menu

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#46]
Since I have Parse-This incorporated into Yarns, and I have IndieWeb Post Kinds installed on my site, Parse-This seems to be adding itself to the dashboard menu twice:

![Screen Shot 2019-06-21 at 11 58 18 AM](https://user-images.githubusercontent.com/12275399/59938924-5eb27d00-9424-11e9-92a7-7ebc261276c1.png)

Not sure if this means I'm calling Parse-This incorrectly in Yarns, or if it should be addressed within Parse-This itself.

I suppose this could be addressed by checking to see if there's already a menu item for Parse This before adding another

**Comment by dshanske** [comment]
I think I need to make some changes to the new load and send a PR to you. You need to remove require/include and just include the autoload file and it will figure out the rest.

**Comment by dshanske** [comment]
Either way, hope to release the new Post Kinds this weekend

**Comment by jackjamieson2** [comment]
Sounds great!

**Comment by dshanske** [comment]
This one still happening?

**Comment by jackjamieson2** [comment]
This looks to be fixed!
