### ISSUE TITLE
Infer summary from content if no explicit summary property

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#47]
per our discussion at https://chat.indieweb.org/wordpress/2019-06-21#t1561138441069700

Since Post Kinds relies on `summary` to display excerpts for likes, etc., several of my responses lack context - examples at https://jackjamieson.net/kind/like/

As you suggested, populating the summary field based on content would solve this issue

**Comment by dshanske** [comment]
What if there is no content? although I suppose neither summary nor content is unlikely.

**Comment by jackjamieson2** [comment]
Hmm, I guess still possible, though. e.g. when responding to posts that are already responses.

In my opinion, using content if no explicit summary is available would probably resolve most cases.

**Comment by dshanske** [comment]
I think I have a provision for that in the code. I am doing some cleanup next.

**Comment by Cambridgeport90** [comment]
I'll be keeping an eye on this one; affects my site as well.

**Comment by dshanske** [comment]
I did have a provision in the code for this, but I had another setting that would remove it if it was identical to the content. I removed that. We'll see what happens.
