### ISSUE TITLE
Can't include SimplePie in plugin added to the WordPress Plugin repository

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/parse-this#53]
WordPress's plugin review team replied to my submission of Yarns Microsub Server.

 It turns out that including a new version of SimplePie is a problem.  Do you have any thoughts on how to address this?  My sense is that the older version of SimplePie included with WordPress is not going to cut it, or would at least require a substantial rewrite of Parse-This, is that accurate?

> ## Including Libraries Already In Core
> 
> Your plugin has included a copy of a library that WordPress already includes.
> 
> WordPress includes a number of useful libraries, such as jQuery, Atom Lib, SimplePie, PHPMailer, PHPass, and more. For security and stability reasons, plugins may not include those libraries in their own code, but instead must use the versions of those libraries packaged with WordPress.
> 
> While we do not YET have a decent public facing page to list all these libraries, we do have a list here: https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/core/credits/wp-52.php#L443
> 
> Some examples from your plugin:
> 
> yarns-microsub-server-1.0.1/lib/parse-this/lib/simplepie/

**Comment by dshanske** [comment]
Can you ask them to reconsider and advise that you will remove if https://core.trac.wordpress.org/ticket/36669 is actioned

**Comment by dshanske** [comment]
And that the code is specifically limited to only be launched by your code and not globally included.

**Comment by jackjamieson2** [comment]
Will do, I'll let you know what they say. Thanks!

**Comment by jackjamieson2** [comment]
Exception was granted! Thanks for the advice.

I'll let you know once I've uploaded the plugin - probably Monday
