### ISSUE TITLE
Log flodded with PHP Warning: mb_strlen(): Unknown encoding

### ISSUE THREAD

**Issue by bekopharm** [dshanske/parse-this#70]
Version 012b14709c9b7bc1d1dc4473b93c3adf14d1a62d (happens also with the snapshot shipped with post-kinds `3.4.3`)
PHP `7.4`

PHP log is flodded with multiple warnings of:

> PHP Warning:  mb_strlen(): Unknown encoding &quot;1&quot; in wp-content/plugins/indieweb-post-kinds/lib/parse-this/includes/class-parse-this-base.php on line 47

**Comment by dshanske** [comment]
Interesting... I'll get on it...I found the other issue quickly

**Comment by dshanske** [comment]
Should be gone now.
